site:
  title: "Factory Floor Tycoon: Agentic AI Demo"
  url: https://localhost
  start_page: modules::index.adoc

content:
  sources:
    - url: ..
      start_path: docs/content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/patternfly-6/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./docs/content/supplemental-ui

asciidoc:
  attributes:
    page-pagination: ''

output:
  dir: ./www
